### PR TITLE
Analog dials for pressure and speed rework

### PR DESCRIPTION
**Pull request by garyStofer**
Here are the changes I did this week to get the analog dials to control cutting pressure and speed. 

The 5 steps of the dials map to the middle  of the  pressure and speed ranges and provide the initial setting when the machine is turned on. The pressure and speed can the then be adjusted in 5 steps by turning the respective dial. The full range of the settings can be accessed with the +/- buttons on the keyboard. The +/- affects the setting for the last touched dial. 

Also modified the cutting force, so that the solenoid doesn't get over saturated. Used to be that steps 8,9,and 10 produced the same (maxed out) cutting force because the solenoid was maxed out of magnetic flux at step "7.5"

Added a pen down feature from the keypad to measure actual pen force.
No changes to the display code in this branch.

### CODE REVIEW

**Comment by markawilliamson** [comment]
Thats awesome, thanks!

**Comment by garyStofer** [comment]
Your welcome, now you have to figure out why yours doesn’t work and how to merge it. 

Did you ever get any encouraging words from Make The Cut people about getting HPGL integrated in their SW? 

While Inkscape and HPGL works great, I think that maybe I look into having it understand GPGL as well. Then all the Graphtek, Silhouette stuff will work with it too.  I use a Silhouette to cut PCB stencils with right now and it comes with a great software package. (I'm always struggling with Inscape's different use of mouse and keyboard features.) 

Cheers 

Gary

**Comment by markawilliamson** [comment]
The problem is, all those software/machine combos are "proprietary" and the
software won't recognize our machines unless we tell it we are something
we're not, and that is where the grey area is.

The lawsuit that Provo filed against make the cut and sure cuts alot was
based on the software makers reverse engineering the communications
protocol and the (in at least one case) decompiled .net code.

They basically told me that It should work with their software as is if I
selected the US Cutter driver.  But that didn't work.

http://sourceforge.net/p/inkcut/feature-requests/6/

yeah looks like GPGL would be a good add on, then using the RAW printer
driver trick, it should be easy to print/cut to it.

can you send me a picture of one of your PCB stencils?  I'm curious...

I spent all weekend on my 3d printers... lol .  was going to "cut out" some
time for the cutters but didnt get to it.

**Comment by garyStofer** [comment]
It's difficult to take good pictures of masks since they are see through. Here are two pics from one of them. The QFP in the corner is 5mm square and has 24 pins underneath.  I go from Eagel CAD gerber stencil layer direct to a graphtec output to the cutter. The tool is a Python based tool and it ads blade straightening cuts outside the work area, so it never turns the blade when it cuts. I have not tried the Roland based knives yet, but I think the Silhouette knives are finer, just looking at it. 

I cut the stencils into ~0.007" Mylar you can get at any fine bakery. They use it as stiffening around the outside of some cakes. Comes in 4" tall  sections. 

So the Gerber to Graphtec tool is definitely not sensitive to the actual cutter attached, or at least it would be trivial to change the comparison since it's in Python.  

As far as using Silhouettes software to print to an other device,  I think they are pretty open to that already. I recall using their Software and print to a regular printer. And you can export to various formats and print/cut from there,  or the print to file  mode etc.  Also they don't have any cartridge sales they want to protect like CriCut has. 

Yeah, I tried Make The Cut as well and found that it didn't work.  

Gary

**Comment by markawilliamson** [comment]
I'll download and test these before I do a merge.  thanks for continuing the effort and applying knowledge to the project!

**Comment by garyStofer** [comment]
Thanks

Yes, please do and make sure to skip my LCD code when merging. I'm not a great GIT expert, but I think you have to merge the diffs between my last and my LCD4x40 commit. 

I was successful in cutting 1.5mm rubberized cork gaskets with the machine. 5 passes did it beautifully.  I will add some timeout feature so that the motors stay engaged between individual cuts, so that there is not chance of them loosing a step in between multiple cuts into the same material. 

These are really well built machines, mechanically at least. I might have to get an other one ...

Cheers
Gary

**Pull request merged**
